---
title: "Generating Random Numbers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In order to simulate random processes, we need to be able to generate random numbers

### *Using the Inverse CDF to generate numbers from a distribution*
In order to simulate a random process, we want to be able to generate random numbers. If we can generate random numbers uniformly distributed between 0 and 1, then we can use the inverse cdf of a probability distribution to generate random numbers from that probability distribution. 

### *Modular*
Modular Arithmetic: we say two numbers are congruent modulo (or mod) n if their difference is divisible by n. Arithmetic modulo n collapses all of the integers into n "congruence classes" or "equivalence classes."

For example, if we do arithmetic mod 7, then we have the following congruence classes

Integers equivalent/congruent to 0:  $\{…,-28, -21, -14, -7, 0, 7, 14, 21, 28, 35, …\}$ 

Integers congruent to 1:  $\{…,-27, -20, -13, -6, 1, 8, 15, 22, 29, 36, …\}$

Integers congruent to 2:  $\{…,-26, -19, -12, -5, 2, 9, 16, 23, 30, 37, …\}$

Integers congruent to 3:  $\{…,-25, -18, -11, -4, 3, 10, 17, 24, 31, 38, …\}$

Integers congruent to 4:  $\{…,-24, -17, -10, -3, 4, 11, 18, 25, 32, 39, …\}$

Integers congruent to 5:  $\{…,-23, -16, -9, -2, 5, 12, 19, 26, 33, 40, …\}$

Integers congruent to 6:  $\{…,-22, -15, -8, -1, 6, 13, 20, 27, 34, 41, …\}$

You probably gave up division with remainders long ago, so recall: 
When you divide $k$ by $n,$ you are finding numbers $q$ (for quotient) and $r$ (for remainder) such that $k = qn + r$  where $r$ is between $0 and n – 1.$

Example: divide -18 by 7

We want to find a multiple of 7 just less than -18 so that we can add a small, positive, remainder to that multiple to get -18. Because -21 is a multiple of 7 just less than -18, $-18 = -3\cdot7 + 3$. 

What does that say about -18 and 3 in mod 7 arithmetic? 
Because -18 -3 = -21, which is divisible 7, -18 and 3 are in the same congruence class modulo 7.

In general, the remainder when you divide by the modulus will give you a representative of the congruence class that is at least 0 and no more than the modulus minus 1. 

Example: divide – 23 by 5. 


What does that say about -23 and 2 in mod 5 arithmetic 

Again -23 and 2 are in the same congruence class modulo 5, because -23 - 2 = -25 and -25 is divisible by 5. 

Given the modulus, $n,$ you can always find a number congruent to integer $k$ that is in the set $\{0, 1, …, n – 1\}$  by finding the remainder when you divide $k$ by $n$ (or add or subtract multiples of $n$ until you have a number in the set $\{0, 1, 2, …, n –1\}$.)  

We can add or subtract two numbers in arithmetic mod $n$: just add or subtract them as normal and then find the remainder when you divide by $n$ (or add or subtract multiples of $n$ until you have a number in the set $\{0, 1, 2, …, n –1\}.$)

For example    19 + 9 mod 7  = 
19 + 9 = 28 and 28 mod 7 is congruent to 0, so 19 + 9 mod 7 = 0. 

Note that if you use any representatives from the congruence classes of 19 and 9 you'll get the same result.

19 mod 7 = 5 and 9 mod 7 = 2, so 19 + 9 mod 7 = 5 + 2 mod 7 = 0.

Example: what is 7 – 11 mod 5? 
7 mod 5 is 2 and 11 mod 5 is 1, so 7 - 11 mod 5 = 2 -1 mod 5 = 1. 

The =mod(number, n) command in Excel will do this for you. You could enter =mod(7-11, 5) in a cell and get 1. 

We can multiply two numbers in arithmetic mod $n$: just add or subtract them as normal and then find the remainder when you divide by $n$ (or add or subtract multiples of $n$ until you have a number in the set $\{0, 1, 2, …, n –1\}.$)

Example: what is $19 \cdot 11 \mod 7?$  
First, $19 \cdot 11 = 209$ and then $209 = 29\cdot 7 + 6$, so $209 \mod 7 = 6. 

Does it matter if we use something congruent to 19 instead? No
19 is congruent to 5 mod 7 and 11 is congruent to 4 mod 7, so 
$19 \cdot 11 \mod 7 = 5 \cdot 4 \mod 7 = 20 \mod 7 = 6.$



*Definition:* a *Linear Congruential Generator (LCG)* is a process for generating uniform random numbers that uses modular arithmetic. 
1 Start by picking numbers $m$ (slope), $b$ (intercept), and $n$ (the modulus.) 
2. Pick a seed (or starting value), $x_1,$ maybe by using the time or some other number that won't always be the same. (In Excel =now() will get you the date and time, which you can format as a number. =round and =floor can help trim things off.) 
3. Generate the next number in your random sequence by computing $x_2 = mx_1+b \mod n$
4. Keep repeating this process, i.e. $x_{k+1}=mx_k+b\mod n,$ to generate a sequence of pseudorandom numbers between 0 and $n – 1.$ 
This process will always repeat once you get to a number you've seen before, so it is not really random, and that's why we say "pseudorandom".  If all the numbers are between 0 and $n – 1,$ how far can we go between? If you generate $n + 1$ numbers between 0 an and $n -1 $, then it is like fitting $n+1$ pigeons into $n$ holes. Maybe there are lots of holes with more than one pigeon, but there is at least one hole with two pigeons. So, after you've generated $n + 1$ you must have hit a repeat. That means the very best case is that the period is equal to the modulus, $n$

When $b \neq 0,$ correctly chosen parameters allow a period equal to $n,$ for all seed values. This will occur if and only if:
n and b are relatively prime (share no common primes.)
m – 1 is divisible by all prime factors of n,
m – 1 is divisible by 4 if n is divisible by 4.
Definition: a Multilinear Congruential Generator (LCG) is a process for generating uniform random numbers that uses modular arithmetic. 
1 Start by picking numbers $a_1,a_2,\ldots,a_j$ (slopes), $b$ (intercept), and $n$ (the modulus.) 
2. Pick $j$ seeds (or starting values), $x_j,x_j-1,\ldots,x_1$ (maybe by using the time or some other number that won't always be the same. 
3. Generate the next number in your random sequence by computing $a_1x_j+a_2x_{j-1}+\cdots+a_jx_1+b\left(mod\ n\right)$ 
4. Keep repeating this process to generate a sequence of pseudorandom numbers between 0 and $n – 1.$ 
This process will always repeat once you get to a sequence of $j$ numbers you've seen before, so it is not really random, and that's why we say "pseudorandom". 


From last time:   Let $Y~U\left[0,1\right]$  (this is shorthand for $Y$ is distributed uniformly on the closed interval from 0 to 1.) 
What is the pdf for $Y?$ 
For $U[0, 1]$, the pdf is $f(x) = \left\{\begin{matrix} 1, & 0 \le x \le y\\ 0, & \text{otherwise}\\\end{matrix}\right.$

What is the cdf for $Y?$
Integrating the pdf for $Y$, we have $F(x) = \int_{-\infty}^x{f(t)dt} = \left\{\begin{matrix} 0, &  x < 0 \\ x, & 0 \le x \le 1 \\ 1, & x > 1\\\end{matrix}\right.$

What is $Pr(Y \le y)?$  For $y$ between 0 and 1,  $Pr(Y \le y) = y$

Let $F$ be the cdf for a continuous random variable. 

Let $Z$ be the random variable defined by $Z=F^{-1}\left(Y\right)$
For some specific number, $z,$ in the domain of $F,$ what is $\Pr{\left(Z\le z\right)}?$
$\Pr{\left(Z\le z\right)}\ =\Pr{\left(F^{-1}\left(Y\right)\le z\right)}=\Pr{\left(Y\le F\left(z\right)\right)}=F\left(z\right)$
In other words, $F$ is the cdf of $Z,$ so $Z$ is a random variable with the distribution whose cdf is $F.$ 
How would this work for a discrete random variable?





